/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package funcify.graphql.service

import com.sun.tools.javac.util.StringUtils
import funcify.graphql.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
}
