---
spring:
  application:
    name: funcify-feature-eng
server:
  servlet:
    context-path: /funcify
  port: 8343

logging:
  level:
    funcify.feature: INFO # Can toggle if debug level needed during local testing

funcify-feature-eng-service:
  system-default-time-zone: UTC
